baseURL: "https://piotrwolinski.github.io/portfolio-page/"
languageCode: "en-us"
title: "Piotr Wolinski"
theme: hugo-profile-custom

googleAnalytics: G-123456789

pagination:
  disableAliases: false
  pagerSize: 3
  path: page

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true  
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

params:
  title: "Portfolio & personal blog"
  description: Portfolio & personal blog
  favicon: /favicon.png
  staticPath: "https://piotrwolinski.github.io/portfolio-page/"  # The path to serve the static files from

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  math: true

  theme:
    disableThemeToggle: false
    defaultTheme: "dark"

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  navbar:
    stickyNavBar:
      enable: true
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hey! It's great to see you, I'm"
    title: "Piotr"
    subtitleHigher: "Software Engineer"
    subtitleLower: "" # "CS student"
    content: | 
      Welcome to my personal space, please take a look around and   
      if something (some post from my blog for instance) is of interest to you,  
      feel free to reach out.
    image: images/main_profile_picture.jpg
    button:
      enable: true
      name: "Resume"
      url: "cv/Piotr_Wolinski_CV.pdf"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/PiotrWolinski
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/piotr-wolinski/

  # About
  about:
    enable: true
    title: "About Me"
    content: |-
      Changing stuff and seeing what happens.  
      Trying to do it fast enough to call it Machine Learning.
        
      Software engineer with 3 years of experience and a passion for high performance and simple to use systems. Loves experimenting with new technologies and picking right tools for the given job. Still mastering trully pragmatic approach. Meanwhile working on obtaining a MSc from University of Zurich. 
    skills:
      enable: false
      title: "My technology stack:"
      items:
        - "Python"
        - "Docker"
        - "C++"
        - "JavaScript"
        - "Vue"

  # Experience
  experience:
    enable: true
    items:
      - company: "Sika AG"
        positions:
          - job: "Working Student Data Engineer"
            company: "Sika AG"
            companyUrl: "https://www.sika.com/"
            date: "July 2024 - Present"
            info:
              enable: false
            content: |-
              I'm working part time as a Data/Software Engineer at Sika AG, where I'm working on multiple internal projects related to data. Additionally I'm sharing my python and SE related knowledge by leading interactive sessions with other juniors.

              Skills showed:
              - Python
              - Git
              - Machine Learning
              - Algorithms
              - Data Processing
              - Leadership


      - company: "Verity AG"
        positions:
          - job: "Working Student Software Engineer"
            company: "Verity AG"
            companyUrl: "https://verity.net/" 
            date: "August 2023 - June 2024"
            info:
              enable: false
            content: |
              I was part of the Application Operations team and my main tasks were keeping existing software and internal tools running and also improve them with new functionalities. 
              During this time I really honed my python skills, learning from my amazing colleagues and also built some more self-confidence. I believe this really allowed me to become more aware and more pragmatic software engineer.


              My biggest achievements are:
              - Integrated proximity based clustering into existing 3D visualization tool to improve data quality processes
              - Developed a tool to streamline reports generation process reducing time spent on the creation part by more than 90%
              - Accelerated internal tools with numerous features and improvements streamlining QA processes, but also increasing productivity and decreasing frustration of people using them
              - Refactored large portion of the client facing REST API to ensure smoother development

              Technical skills I showed:
              - Python (pandas, FastAPI, pydantic, scikit-learn)
              - Data structures, problem solving
              - Git, Linux
              - Code review, critical thinking

              Soft skills:
              - Work organization
              - Time management
              - Collaboration


      - company: "Deeptale"
        positions:
          - job: "Junior Machine Learning Engineer"
            company: "Deeptale.ai"
            companyUrl: "https://deeptale.ai/"
            date: "February 2023 - May 2023"
            info:
              enable: false
            content: |
              As a part of a development team I am mostly focused on developing microservices and APIs linking various components of Deeptale infrastructure. 
              Also I was the main developer of the QA Platform which main goal was to enhance graphics team performance by adding user friendly interface and well-optimized REST API endpoints.

              Main achievements:
              - Developed QA web application that had a significant impact on the performance of the graphics team
              - Proposed & implemented architecture for microservices
              - Improved API design and configurability

              Tech stack:
              - Python (FastAPI, Pydantic, Celery, poetry)
              - Docker & Docker Compose
              - Google Cloud Platform
              - Vue, JavaScript
              - Make

              Other skills:
              - REST API design
              - Data structures
              - Algorithms
              - Machine Learning
              - Taking ownership

      - company: "STX Next"
        positions:
          - job: "Python Developer"
            company: "STX Next"
            companyUrl: "https://www.stxnext.com/"
            date: "July 2022 - January 2023"
            info:
              enable: false
            content: |
              During my time in STX I had the opportunity to work in two separate areas:

              Data Engineering:

              While working with data processing involving ETL pipelines, I managed to fix an inconsistency in one of the client's datasets by firstly gathering, transforming and analysing necessary data and then preparing and running loaders to make it live. 

              Development of internal management app:

              Worked together with a team of backend and frontend developers on enhancing user experience and implementing requested features. This involved bug fixes, adding new features and improving existing ones (ie. extending Google calendar integration). Tech stack consisted of Django, Pyramid, SQLAlchemy and Docker. My greatest achievement was that users could use internal systems more efficiently and without any additional stress.
                
              Technology stack:
              - Python (pandas, plotly, Django, Pyramid, SQLAlchemy)
              - Docker & Docker Compose
              - Jupyter
              
      - company: "Intel corp"
        positions:
          - job: "Deep Learning Software Engineer Intern"
            company: "Intel"
            companyUrl: "https://www.intel.com/content/www/us/en/homepage.html"
            date: "October 2021 - June 2022"
            featuredLink:
              enable: true
              name: "Project I was working on"
              url: "https://mxnet.apache.org/"
            info:
              enable: true
              content: Later on changed team and started working on DL framework.
            content: |
              Contributed to open-source MXNet Deep Learning Framework, by adding new optimization features, general improvements and bug fixes. Few honorable mentions are: implemented backward adaptive pooling kernels, unified viewing of the computational graphs by including fused operators, added options for new activations functions for certain operators.

              I learned a lot during this time, however I was still not sure whether such low-level approach to Machine Learning is for me. Nevertheless, it was a great experience which allowed me to taste a production-grade C++.
                
              Technology stack:
              - C++
              - Python
              - Docker
              - Make

          - job: "Software Engineer Intern"
            company: "Intel"
            companyUrl: "https://www.intel.com/content/www/us/en/homepage.html"
            date: "July 2021 - September 2021"
            info:
              enable: true
              content: It was my first job as a software developer.
            content: |
              Together with my team we were working on full-stack web application with Vue, Flask and MongoDB.  
                
              My greatest achievement was rework of a certain data aggregating endpoint. With my implementation it was 30 times faster on average and requests were no longer timing-out.
                
              Technology stack:
                - Python (Flask, pymongo)
                - Javascript, Vue
                - Docker & Docker Compose

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "MSc in Data Science"
        school:
          name: "University of Zurich"
          url: "https://www.ifi.uzh.ch/en.html"
        date: "August 2023 - December 2025"
        GPA: "5.0 / 6.0"
        content: |-
          Focused on major in Data Science to combine theoretical knowledge of AI and ML with hands-on experience in software systems development. My research interest is mostly focused on Computer Vision and robotics.

          Relevant coursework:
          - Deep Learning
          - Computer Vision @ETH
          - Vision Algortihms for Mobile Robotics
          - Vision Based Drone Flight
          - Reinforcement Learning
          - Systems for Data Science

      - title: "BEng in Computer Science"
        school:
          name: "Gdańsk University of Technology"
          url: "https://pg.edu.pl"
        date: "September 2019 - February 2023"
        GPA: "4.5 / 5.0"
        content: |-
            - Scholarship due to the excellent grades after 2nd and 3rd year
            - Prepared and executed a university budget project, more information can be found **[under this link](https://pg.edu.pl/budzet_obywatelski/projekty-do-realizacji/edycja-2022/projekt-211-2022)**.
            - Course Student Representative throughout the studies

  # Achievements
  achievements:
    enable: true
    items:
      - title: 3rd place during BEST Career Meeting Hackathon 2022
        content: Together with my team we won 3rd place during this contest. Tasks I was focused on involved mostly image processing.
      - title: AI Games Hackathon 2022
        content: Scored 4h as a team in Aircraft Trajectory Prediction Challange. Had a significant impact on team performance, by efficiently processing provided data with Python.
      # - title: Hugo Profile
      #   content: Developed a theme and getting 1K+ downloads per month.
      #   url: "https://github.com/gurusabarish/hugo-profile"


  # courses
  courses:
    enable: true
    items:
      - title: "Fundamentals of Accelerated Computing with CUDA Python"
        image: images/python-cuda.png
      - title: "Kaggle: Machine Learning Explainability"
        image: images/MachineLearningExplainability.png
      - title: "Kaggle: Intermediate Machine Learning"
        image: images/IntermediateMachineLearning.png
      - title: "Kaggle: Intro to Machine Learning"
        image: images/IntroToMachineLearning.png
      - title: "DataCamp: Intro to ChatGPT"
        image: images/IntroToChatGPT.png
      - title: "DataCamp: Introduction to Airflow in Python"
        image: images/IntroToAirflow.png
      - title: AZ-900 Microsoft Azure Fundamentals
        image: images/AZ900.png
    
  # projects
  projects:
    enable: true
    items:
      - title: MicroPython for edge AI inference
        content: Diploma project, conducted together with my colleague, in which the main goal was to highlight Artificial
                  Intelligence applications on edge devices, ie. microcontrollers with very limited resources. Device we
                  created was based on two ESP32 microcontrollers and MicroPython language and was able to perform
                  image recognition using quantized CNNs together with TensorFlow Lite framework.
        image: images/micropython_project.jpeg
        badges:
          - "Python"
          - "Tensorflow Lite"
          - "Machine Learning"
        links:
          - icon: fab fa-github
            url: https://github.com/mkuczynski11/micropython-tflite
      - title: Fourier features for high frequency functions ‐  PyTorch implementation 
        content: Implementation of a paper which laid the foundations for NeRFs - novel 3D reconstruction method.
        image: images/fourier_features.png
        badges:
          - "Pytorch"
          - "Machine Learning"
        links:
          - icon: fab fa-github
            url: https://github.com/PiotrWolinski/image-regression-with-fourier-features
      - title: Real-time drone detection
        content: |
          Together with my colleagues we trained a YOLOv5 model for a robust drone detection task. My contribution included proposing the real-world data annotation pipeline, implementing simulation data generator and coordinating group efforts. In the end our detector outperformed the reference model by a significant margin in robustness and accuracy.
        image: images/drone_detection.png
        badges:
          - "Python" 
          - "Computer Vision"
          - "Leadership"
        links:
          - icon: fab fa-github
            url: https://github.com/JorgeOrtizV/drone_tracking/blob/generate-poses/generate_poses.ipynb
      - title: Harris corners in rust
        content: |
          Very verbose implementation of harris corner detector, mainly for purpose of learning rust. Work is still in progress and from time to time I will add new commits, but current implementation is already working.
        image: images/harris_corners_rust.png
        badges:
          - "Rust"
          - "Computer Vision"
        links:
          - icon: fab fa-github
            url: https://github.com/PiotrWolinski/rust-harris-corners


  #Contact
  contact:
    enable: true
    content: Something caught your attention? Write me an email and I will get back to you.
    email: piotr.wolinski.2017@outlook.com
    btnName: Email

  footer:
    recentPosts: true
    socialNetworks:
      github: https://github.com/PiotrWolinski
      linkedin: https://www.linkedin.com/in/piotr-wolinski/
